import { MachineExercise } from "../types";

export const INITIAL_MACHINES: MachineExercise[] = [
  {
    id: "m_cinta_correr",
    name: "Cinta de Correr (Treadmill)",
    category: "Cardio",
    isCardio: true,
    description: "Cinta motorizada para carrera continua o intervalos (HIIT) por tiempo e intensidad.",
    imageUrl: "https://images.unsplash.com/photo-1578768079052-aa76e520028b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_bici_estatica",
    name: "Bicicleta Estática / Spinning",
    category: "Cardio",
    isCardio: true,
    description: "Pedaleo cardiovascular con ajuste de resistencia magnética por tiempo y nivel.",
    imageUrl: "https://images.unsplash.com/photo-1538805060514-97d9cc17730c?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_eliptica",
    name: "Máquina Elíptica",
    category: "Cardio",
    isCardio: true,
    description: "Cardio de bajo impacto articular con trabajo coordinado de brazos y piernas.",
    imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_remo_cardio",
    name: "Remo Indoor (Concept2)",
    category: "Cardio",
    isCardio: true,
    description: "Trabajo cardiovascular completo de tracción y empuje por tiempo, ritmo e intensidad.",
    imageUrl: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_escaladora",
    name: "Escaladora (StairMaster)",
    category: "Cardio",
    isCardio: true,
    description: "Escalones continuos de alta intensidad para capacidad cardiovascular y glúteos.",
    imageUrl: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_prensa_leg",
    name: "Prensa de Piernas (Leg Press)",
    category: "Piernas",
    description: "Plataforma inclinada a 45° para trabajo pesado de cuadriceps y glúteos.",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_jalon_polea",
    name: "Jalón al Pecho en Polea",
    category: "Espalda",
    description: "Polea alta con agarre ancho para desarrollo del dorsal y espalda superior.",
    imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_pec_deck",
    name: "Contractor de Pecho (Pec Deck)",
    category: "Pecho",
    description: "Aislamiento pectoral mediante movimiento guiado de apertura y cierre.",
    imageUrl: "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_press_hombros",
    name: "Press de Hombros en Máquina",
    category: "Hombros",
    description: "Empuje vertical con carga guiada para deltoides con estabilidad lumbar.",
    imageUrl: "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_extension_triceps",
    name: "Polea Alta para Tríceps",
    category: "Tríceps",
    description: "Extensión de codos en polea alta con cuerda para aislar tríceps.",
    imageUrl: "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_curl_scott",
    name: "Curl Bíceps Banco Scott",
    category: "Bíceps",
    description: "Flexión de codo apoyado para máximo estímulo en el vientre del bíceps.",
    imageUrl: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_curl_femoral",
    name: "Curl Femoral Tumbado",
    category: "Piernas",
    description: "Flexión de rodilla tumbado para tensión constante en isquiotibiales.",
    imageUrl: "https://images.unsplash.com/photo-1574680096145-d05b474e2155?q=80&w=600&auto=format&fit=crop",
  },
  {
    id: "m_extension_cuadriceps",
    name: "Extensiones de Cuádriceps",
    category: "Piernas",
    description: "Extensión de rodilla sentado para trabajo enfocado en cuádriceps.",
    imageUrl: "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop",
  }
];
